/**
 * Sourcing content for the public site.
 *
 * Categories and products are AfriLynq's own list, supplied 6 September 2026.
 * Harvest windows, trading units and minimum order quantities reflect how
 * these goods actually move out of West and East Africa. AfriLynq should
 * confirm the units and minimums against its own supplier base before launch
 * and correct anything that does not match.
 *
 * Nothing here claims a supplier count, a delivery percentage, an escrow
 * facility or a customer testimonial. None of those exist yet, and this is a
 * United Kingdom site where an unsubstantiated claim is a regulatory exposure
 * as well as a credibility one.
 */

export const MONTHS = [
  "Jan", "Feb", "Mar", "Apr", "May", "Jun",
  "Jul", "Aug", "Sep", "Oct", "Nov", "Dec",
] as const;

export type Availability = "peak" | "available" | "none";

export interface Product {
  name: string;
  /** Local or common name, shown alongside the trade name. */
  localName?: string;
  /** Photo filename stem: public/photos/products/<slug>.jpg */
  slug: string;
  origins: string[];
  /** Twelve entries, January to December. */
  calendar: Availability[];
  unit: string;
  minimumOrder: string;
  note: string;
}

export interface Category {
  slug: string;
  name: string;
  summary: string;
  intro: string;
  /** What a buyer typically needs to state when enquiring. */
  specify: string[];
  products: Product[];
}

function months(peak: number[], available: number[] = []): Availability[] {
  return Array.from({ length: 12 }, (_, i) => {
    const m = i + 1;
    if (peak.includes(m)) return "peak";
    if (available.includes(m)) return "available";
    return "none";
  });
}

const ALL = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12];
const except = (...m: number[]) => ALL.filter((x) => !m.includes(x));

export const CATEGORIES: Category[] = [
  {
    slug: "grains-and-seeds",
    name: "Grains and seeds",
    summary:
      "Sesame, soybeans, groundnuts, beans, millet and sorghum, harvested from October and traded by container load.",
    intro:
      "Grains and oilseeds are the backbone of West African agricultural export. They store well, which means the buying decision turns on grade and cleanliness rather than on shipping speed. Most of the crop is harvested between October and February, and quality is judged on three numbers: moisture, foreign matter and broken percentage.",
    specify: [
      "Moisture content, foreign matter and broken percentage",
      "Purity, and for sesame whether white or brown",
      "Bagged or bulk, and the bag weight",
      "Whether fumigation before loading is required",
      "Aflatoxin limits where they apply, particularly for groundnuts",
      "Incoterm and load port",
    ],
    products: [
      {
        name: "Sesame seed",
        localName: "Ridi, Ekuku",
        slug: "sesame",
        origins: ["Nigeria", "Ethiopia", "Tanzania"],
        calendar: months([12, 1, 2], [3, 4, 11]),
        unit: "Metric tonne",
        minimumOrder: "One 20 ft container, about 25 tonnes",
        note: "White and brown varieties, sold on purity. The Nigerian crop is harvested from November and ships through to about April.",
      },
      {
        name: "Soybeans",
        slug: "soybeans",
        origins: ["Nigeria"],
        calendar: months([10, 11, 12], [1, 9]),
        unit: "Metric tonne",
        minimumOrder: "One 20 ft container",
        note: "Non genetically modified crop. Protein and oil content should be agreed before shipment rather than tested on arrival.",
      },
      {
        name: "Groundnuts",
        localName: "Epa, Gyada, Arachide",
        slug: "groundnuts",
        origins: ["Nigeria", "Ghana"],
        calendar: months([11, 12], [10, 1, 2]),
        unit: "Metric tonne",
        minimumOrder: "One 20 ft container",
        note: "Blanched, raw or in shell. Aflatoxin testing is normally required for the United Kingdom and should be agreed up front.",
      },
      {
        name: "Beans",
        localName: "Ewa, Wake, Niebe",
        slug: "beans",
        origins: ["Nigeria"],
        calendar: months([10, 11, 12], [1, 2]),
        unit: "Metric tonne",
        minimumOrder: "One 20 ft container",
        note: "Brown and white cowpea. Pesticide residue limits are strict for this crop, so confirm the treatment history with the supplier.",
      },
      {
        name: "Millet",
        localName: "Maiwa, Dagusa",
        slug: "millet",
        origins: ["Nigeria"],
        calendar: months([10, 11], [9, 12, 1]),
        unit: "Metric tonne",
        minimumOrder: "One 20 ft container",
        note: "Pearl millet, sold whole or milled. Growing United Kingdom demand for gluten free flour and for bird feed.",
      },
      {
        name: "Sorghum",
        localName: "Oka Baba, Dawa",
        slug: "sorghum",
        origins: ["Nigeria"],
        calendar: months([11, 12], [10, 1, 2]),
        unit: "Metric tonne",
        minimumOrder: "One 20 ft container",
        note: "White and red varieties. Used mainly for brewing and animal feed.",
      },
      {
        name: "Fonio",
        localName: "Acha",
        slug: "fonio",
        origins: ["Guinea", "Nigeria", "Senegal", "Mali", "Burkina Faso"],
        calendar: months([9, 10, 11], [1, 2, 3, 4, 5, 6, 7, 8, 12]),
        unit: "Metric tonne",
        minimumOrder: "1 tonne by air for specialty volumes, or 18 tonnes for a full container",
        note: "White and black fonio. Specify the processing level, raw, husked or parboiled, along with grain purity and moisture percentage.",
      },
      {
        name: "African rice",
        localName: "Ofada, Riz Local",
        slug: "african-rice",
        origins: ["Nigeria", "Ghana", "Mali", "Madagascar", "Sierra Leone"],
        calendar: months([10, 11, 12, 1], [2, 3, 4, 5, 6, 7, 8, 9]),
        unit: "Metric tonne",
        minimumOrder: "20 to 25 tonnes, one 20 ft container",
        note: "Specify the variety, Oryza glaberrima or O. sativa, the percentage of broken grains, parboiled status and aromatic grade.",
      },
      {
        name: "Teff",
        localName: "Teff",
        slug: "teff",
        origins: ["Ethiopia", "Eritrea"],
        calendar: months([11, 12, 1], [2, 3, 4, 5, 6, 7, 8, 9, 10]),
        unit: "Metric tonne",
        minimumOrder: "1 to 5 tonnes, subject to Ethiopian export quotas on raw grain",
        note: "Specify grain colour, ivory, red or brown, purity above 99.9 percent, and any gluten free certification required.",
      },
      {
        name: "African yam bean",
        localName: "Otili, Fio-Fio",
        slug: "african-yam-bean",
        origins: ["Nigeria", "Ghana", "Cameroon"],
        calendar: months([11, 12, 1], [2, 3, 4, 5, 6, 7, 8, 9, 10]),
        unit: "Metric tonne",
        minimumOrder: "1 to 5 tonnes, specialty seed trade",
        note: "State whether the order is for the tuber or the seed pulse, along with seed colour, purity and drying status.",
      },
      {
        name: "Egusi",
        localName: "Egusi, Agushi",
        slug: "egusi",
        origins: ["Nigeria", "Ghana", "Cameroon", "Benin"],
        calendar: months([8, 9, 10, 11], [1, 2, 3, 4, 5, 6, 7, 12]),
        unit: "Metric tonne",
        minimumOrder: "5 tonnes, or 12 to 15 tonnes shelled in a 20 ft container",
        note: "White seed melon. Specify whether machine hulled, hand hulled or whole seed, along with oil purity, moisture below 8 percent and freedom from mould and aflatoxin.",
      },
      {
        name: "White maize",
        localName: "Agbado, Masara",
        slug: "white-maize",
        origins: ["Nigeria", "Ghana"],
        calendar: months([10, 11, 12], [1, 2, 9]),
        unit: "Metric tonne",
        minimumOrder: "One 20 ft container, about 25 tonnes",
        note: "Specify moisture below 13 percent, foreign matter, broken percentage and aflatoxin limits. White maize trades mainly into food milling.",
      },
      {
        name: "Yellow maize",
        localName: "Agbado Pupa",
        slug: "yellow-maize",
        origins: ["Nigeria", "Ghana"],
        calendar: months([10, 11, 12], [1, 2, 9]),
        unit: "Metric tonne",
        minimumOrder: "One 20 ft container, about 25 tonnes",
        note: "Feed and industrial grade. Specify moisture, foreign matter and whether the crop is GMO free.",
      },
      {
        name: "Wheat",
        localName: "Alkama",
        slug: "wheat",
        origins: ["Nigeria", "Ethiopia", "South Africa"],
        calendar: months([3, 4], [1, 2, 5, 12]),
        unit: "Metric tonne",
        minimumOrder: "One 20 ft container",
        note: "Specify protein content, hardness, moisture and screenings. Most African wheat is milled locally, so confirm exportable volumes before pricing.",
      },
      {
        name: "Honey beans",
        localName: "Ewa Oloyin",
        slug: "honey-beans",
        origins: ["Nigeria"],
        calendar: months([10, 11, 12], [1, 2]),
        unit: "Metric tonne",
        minimumOrder: "One 20 ft container",
        note: "Sweet flavoured brown cowpea, the premium variety in diaspora retail. Specify seed size, moisture below 12 percent and fumigation history.",
      },
      {
        name: "Brown beans",
        localName: "Ewa Olotu, Drum",
        slug: "brown-beans",
        origins: ["Nigeria"],
        calendar: months([10, 11, 12], [1, 2]),
        unit: "Metric tonne",
        minimumOrder: "One 20 ft container",
        note: "Large seeded brown cowpea. Specify seed count per 100 grams, coat colour uniformity and pesticide residue treatment.",
      },
      {
        name: "White beans",
        localName: "Ewa Funfun",
        slug: "white-beans",
        origins: ["Nigeria", "Ghana"],
        calendar: months([10, 11, 12], [1, 2]),
        unit: "Metric tonne",
        minimumOrder: "One 20 ft container",
        note: "White cowpea with black eye. Specify eye colour, moisture and weevil free certification.",
      },
      {
        name: "Black beans",
        localName: "Akidi",
        slug: "black-beans",
        origins: ["Nigeria"],
        calendar: months([10, 11, 12], [1, 2]),
        unit: "Metric tonne",
        minimumOrder: "5 tonnes",
        note: "Small black cowpea, sold mainly into diaspora retail. Specify seed size and dryness.",
      },
      {
        name: "Pigeon pea",
        localName: "Fio-Fio, Otili",
        slug: "pigeon-pea",
        origins: ["Nigeria", "Ghana"],
        calendar: months([11, 12, 1], [2, 3, 10]),
        unit: "Metric tonne",
        minimumOrder: "5 tonnes",
        note: "Specify whether split or whole, colour and moisture. Growing demand as a plant protein ingredient.",
      },
      {
        name: "Ofada rice",
        localName: "Ofada",
        slug: "ofada-rice",
        origins: ["Nigeria"],
        calendar: months([10, 11, 12], [1, 2, 3]),
        unit: "Metric tonne",
        minimumOrder: "5 tonnes",
        note: "Unpolished short grain with a distinctive aroma. Specify parboiled status, stone content and the milling date.",
      },
      {
        name: "Acha",
        localName: "Acha, Hungry rice",
        slug: "acha",
        origins: ["Nigeria", "Guinea", "Mali"],
        calendar: months([9, 10, 11], [1, 2, 3, 12]),
        unit: "Metric tonne",
        minimumOrder: "1 tonne",
        note: "Fonio grain sold under its Nigerian name. Specify husked or unhusked, purity and moisture.",
      },
    ],
  },
  {
    slug: "spices-and-botanicals",
    name: "Spices and botanicals",
    summary:
      "Ginger, turmeric, chilli, hibiscus and moringa, dried at origin and shipped through the year.",
    intro:
      "Dried spice is one of the easier categories to begin with, because the goods are stable and order sizes are smaller than for grain. What decides whether a supplier is workable is consistency between the sample and the shipment, and documentation that satisfies United Kingdom food safety requirements on arrival.",
    specify: [
      "Whole, split, sliced or ground",
      "Moisture content, and for ginger the oil content",
      "Sieve or particle size where ground",
      "Whether steam sterilised material is required",
      "Pesticide residue and heavy metal testing requirements",
    ],
    products: [
      {
        name: "Ginger",
        slug: "ginger",
        origins: ["Nigeria"],
        calendar: months([2, 3], except(2, 3)),
        unit: "Metric tonne",
        minimumOrder: "5 tonnes",
        note: "Dried split and sliced. The Kaduna crop is harvested from January, and dried material ships year round from stock with the best pricing shortly after harvest.",
      },
      {
        name: "Turmeric",
        slug: "turmeric",
        origins: ["Nigeria"],
        calendar: months([1, 2, 3], [4, 12]),
        unit: "Metric tonne",
        minimumOrder: "2 tonnes",
        note: "Whole fingers or ground. Buyers usually specify a minimum curcumin content, and it is worth testing before shipment.",
      },
      {
        name: "Chilli",
        slug: "chilli",
        origins: ["Nigeria", "Ghana"],
        calendar: months([12, 1, 2], [3, 11]),
        unit: "Metric tonne",
        minimumOrder: "2 tonnes",
        note: "Whole dried or ground. Heat varies considerably between varieties, so agree a reference sample before pricing.",
      },
      {
        name: "Hibiscus",
        slug: "hibiscus",
        origins: ["Nigeria"],
        calendar: months([12, 1, 2], [3, 11]),
        unit: "Metric tonne",
        minimumOrder: "2 tonnes",
        note: "Sold as sorrel or zobo. Colour and calyx integrity drive the grade. Used for herbal infusions and natural colouring.",
      },
      {
        name: "Moringa",
        slug: "moringa",
        origins: ["Nigeria", "Ghana"],
        calendar: months([], ALL),
        unit: "Metric tonne",
        minimumOrder: "1 tonne",
        note: "Dried leaf, leaf powder and seed. Leaf is available all year; seed follows the October to December window.",
      },
      {
        name: "Alligator pepper",
        localName: "Atare, Ose Oji, Maniguette",
        slug: "alligator-pepper",
        origins: ["Nigeria", "Ghana", "Cameroon"],
        calendar: months([8, 9, 10, 11, 12], [1, 2, 3, 4, 5, 6, 7]),
        unit: "Metric tonne",
        minimumOrder: "500 kg to 1 tonne",
        note: "Grains of paradise. Specify whether whole pods or extracted seed, the seed colour intensity, purity percentage and moisture below 10 percent.",
      },
      {
        name: "Uda",
        localName: "Uda, Negro pepper",
        slug: "uda",
        origins: ["Nigeria", "Ghana"],
        calendar: months([9, 10, 11], [1, 2, 12]),
        unit: "Kilogram",
        minimumOrder: "100 kg",
        note: "Xylopia aethiopica pods, used in pepper soup and post partum preparations. Specify whole pods or ground, and moisture below 10 percent.",
      },
      {
        name: "Ehuru",
        localName: "Ehuru, Calabash nutmeg",
        slug: "ehuru",
        origins: ["Nigeria", "Ghana"],
        calendar: months([8, 9, 10], [1, 2, 11, 12]),
        unit: "Kilogram",
        minimumOrder: "100 kg",
        note: "Monodora myristica seed. Specify shelled or in shell, and whether whole or ground.",
      },
      {
        name: "Uziza seed",
        localName: "Uziza, African black pepper",
        slug: "uziza-seed",
        origins: ["Nigeria"],
        calendar: months([9, 10, 11], [1, 2, 12]),
        unit: "Kilogram",
        minimumOrder: "100 kg",
        note: "Piper guineense. Specify whole peppercorn or ground, and the moisture content.",
      },
      {
        name: "Locust bean",
        localName: "Iru, Dawadawa, Ogiri",
        slug: "locust-bean",
        origins: ["Nigeria", "Ghana", "Cote d Ivoire"],
        calendar: months([6, 7, 8], [1, 2, 3, 9, 10]),
        unit: "Kilogram",
        minimumOrder: "250 kg",
        note: "Fermented Parkia seed. Specify wet, dried or powdered, along with packaging and shelf life, since this is a strongly aromatic product.",
      },
      {
        name: "Aidan fruit",
        localName: "Uyayak, Prekese",
        slug: "aidan-fruit",
        origins: ["Nigeria", "Ghana"],
        calendar: months([10, 11, 12], [1, 2]),
        unit: "Kilogram",
        minimumOrder: "100 kg",
        note: "Tetrapleura tetraptera pods. Specify whole pods or ground, and dryness.",
      },
      {
        name: "Dried pepper",
        localName: "Ata Gbigbe",
        slug: "dried-pepper",
        origins: ["Nigeria", "Ghana"],
        calendar: months([12, 1, 2], [3, 11]),
        unit: "Metric tonne",
        minimumOrder: "1 tonne",
        note: "Sun dried chilli, whole or ground. Specify heat level against a reference sample, and whether steam sterilised material is required.",
      },
      {
        name: "Thyme",
        localName: "Thyme",
        slug: "thyme",
        origins: ["Nigeria", "Kenya", "Egypt"],
        calendar: months([], ALL),
        unit: "Kilogram",
        minimumOrder: "250 kg",
        note: "Dried leaf. Specify cut size, moisture and whether steam sterilised.",
      },
      {
        name: "Curry leaf",
        localName: "Curry leaf",
        slug: "curry-leaf",
        origins: ["Nigeria", "Kenya"],
        calendar: months([], ALL),
        unit: "Kilogram",
        minimumOrder: "250 kg",
        note: "Dried Murraya koenigii leaf. Specify whole leaf or ground, and drying method.",
      },
      {
        name: "Garlic",
        localName: "Ayu, Tafarnuwa",
        slug: "garlic",
        origins: ["Nigeria", "Egypt", "Ethiopia"],
        calendar: months([3, 4, 5], [1, 2, 6, 12]),
        unit: "Metric tonne",
        minimumOrder: "5 tonnes",
        note: "Specify bulb size, cured status, and whether fresh, dried or powdered.",
      },
      {
        name: "Cloves",
        localName: "Kanafuru",
        slug: "cloves",
        origins: ["Tanzania", "Madagascar", "Nigeria"],
        calendar: months([8, 9, 10], [1, 2, 11, 12]),
        unit: "Kilogram",
        minimumOrder: "500 kg",
        note: "Specify hand picked grade, headless percentage and moisture content.",
      },
    ],
  },
  {
    slug: "nuts-and-superfoods",
    name: "Nuts and superfoods",
    summary:
      "Cashew, tiger nuts, shea nuts and bambara nuts, traded on grade and outturn.",
    intro:
      "West Africa supplies a large share of the world's raw cashew, and the smaller crops in this group are growing quickly with United Kingdom demand for plant based ingredients. These are storable goods, so the negotiation is about specification rather than speed.",
    specify: [
      "Grade or outturn, including nut count per kilogram for cashew",
      "Defective percentage and moisture content",
      "Packaging: jute bags, polypropylene or bulk",
      "Whether phytosanitary and fumigation certificates are required",
      "Incoterm and load port",
    ],
    products: [
      {
        name: "Cashew nuts",
        localName: "Kaju",
        slug: "cashew",
        origins: ["Nigeria", "Cote d Ivoire", "Ghana", "Tanzania"],
        calendar: months([3, 4], [2, 5, 6]),
        unit: "Metric tonne",
        minimumOrder: "One 20 ft container, about 16 tonnes",
        note: "Raw in shell, traded on nut count and outturn. The Nigerian and Ivorian crops open in February and thin out by June.",
      },
      {
        name: "Tiger nuts",
        localName: "Aya, Ofio, Chufa",
        slug: "tiger-nuts",
        origins: ["Nigeria"],
        calendar: months([12, 1, 2], [3, 11]),
        unit: "Metric tonne",
        minimumOrder: "5 tonnes",
        note: "Sold dried and whole. United Kingdom demand is driven by plant milk and snack producers.",
      },
      {
        name: "Shea nuts",
        localName: "Ori, Okwuma, Karite",
        slug: "shea-nuts",
        origins: ["Nigeria", "Ghana"],
        calendar: months([7, 8], [6, 9, 10]),
        unit: "Metric tonne",
        minimumOrder: "One 20 ft container",
        note: "Collection runs through the wet season. Processed shea butter is available year round and is listed under oils.",
      },
      {
        name: "Bambara nuts",
        localName: "Okpa, Gurjiya, Voandzou",
        slug: "bambara-nuts",
        origins: ["Nigeria", "Ghana"],
        calendar: months([10, 11, 12], [1, 9]),
        unit: "Metric tonne",
        minimumOrder: "2 tonnes",
        note: "Also called okpa or gurjiya. Sold dried, mainly into diaspora retail and increasingly to plant protein producers.",
      },
      {
        name: "Ogbono",
        localName: "Ogbono, Oro, Ndok",
        slug: "ogbono",
        origins: ["Nigeria", "Cameroon", "Cote d Ivoire", "Gabon"],
        calendar: months([5, 6, 7, 8, 9], [1, 2, 3, 4, 10, 11, 12]),
        unit: "Metric tonne",
        minimumOrder: "1 to 5 tonnes of kernels",
        note: "African mango seed. State whether the order is for fresh fruit or dried seed. For seed, specify the dryness grade and the viscosity quality grade.",
      },
      {
        name: "Kola nut and bitter kola",
        localName: "Oji, Goro, Orogbo",
        slug: "kola-nut",
        origins: ["Nigeria", "Ghana", "Cote d Ivoire", "Cameroon"],
        calendar: months([9, 10, 11, 12, 1], [2, 3, 4, 5, 6, 7, 8]),
        unit: "Metric tonne",
        minimumOrder: "500 kg to 5 tonnes",
        note: "Specify the species, Cola nitida or C. acuminata, or Garcinia kola for bitter kola, along with moisture, nut size grading and mould free treatment.",
      },
      {
        name: "African walnut",
        localName: "Asala, Ukpa",
        slug: "african-walnut",
        origins: ["Nigeria"],
        calendar: months([7, 8, 9], [6, 10]),
        unit: "Kilogram",
        minimumOrder: "250 kg",
        note: "Plukenetia conophora. Specify in shell or shelled, and whether boiled or raw.",
      },
      {
        name: "Ugba",
        localName: "Ugba, Ukpaka, Oil bean",
        slug: "ugba",
        origins: ["Nigeria"],
        calendar: months([1, 2, 3], [4, 11, 12]),
        unit: "Kilogram",
        minimumOrder: "100 kg",
        note: "Sliced fermented African oil bean seed. Highly perishable, so specify packaging, preservation method and shelf life on arrival.",
      },
      {
        name: "Coconut",
        localName: "Aku Oyibo, Agbon",
        slug: "coconut",
        origins: ["Nigeria", "Ghana", "Tanzania"],
        calendar: months([], ALL),
        unit: "Metric tonne",
        minimumOrder: "5 tonnes",
        note: "Specify whole mature nut, desiccated or chips, along with moisture and fat content for processed forms.",
      },
      {
        name: "Dates",
        localName: "Dabino",
        slug: "dates",
        origins: ["Nigeria", "Egypt", "Sudan"],
        calendar: months([9, 10, 11], [1, 2, 12]),
        unit: "Metric tonne",
        minimumOrder: "2 tonnes",
        note: "Specify variety, moisture, sugar content and whether pitted.",
      },
      {
        name: "Yellow tiger nut",
        localName: "Aya Rawaya",
        slug: "yellow-tiger-nut",
        origins: ["Nigeria", "Niger"],
        calendar: months([12, 1, 2], [3, 11]),
        unit: "Metric tonne",
        minimumOrder: "5 tonnes",
        note: "The larger sweeter grade, preferred for tiger nut milk. Specify size grade and moisture below 10 percent.",
      },
      {
        name: "Brown tiger nut",
        localName: "Aya Ruwan Kasa",
        slug: "brown-tiger-nut",
        origins: ["Nigeria", "Niger"],
        calendar: months([12, 1, 2], [3, 11]),
        unit: "Metric tonne",
        minimumOrder: "5 tonnes",
        note: "Smaller and firmer than the yellow grade. Specify size grade, colour uniformity and foreign matter.",
      },
    ],
  },
  {
    slug: "cocoa-and-natural-ingredients",
    name: "Cocoa and natural ingredients",
    summary:
      "Main crop cocoa beans from the Gulf of Guinea, plus locally processed powder and butter.",
    intro:
      "Cocoa is the category where origin is part of the product rather than a logistics detail. Buyers are usually looking for a specific region, and increasingly for traceability back to a co-operative or farm group. Certification is common and should be established before pricing, not after.",
    specify: [
      "Main crop or light crop, and the crop year",
      "Bean count, moisture and defect count",
      "Fat content for butter, and fat percentage for powder",
      "Natural or alkalised, for powder",
      "Certification: organic, Fairtrade, Rainforest Alliance",
      "Whether traceability to co-operative level is required",
    ],
    products: [
      {
        name: "Cocoa beans",
        slug: "cocoa-beans",
        origins: ["Nigeria", "Ghana", "Cote d Ivoire", "Cameroon"],
        calendar: months([10, 11, 12, 1], [2, 3, 5, 6]),
        unit: "Metric tonne",
        minimumOrder: "One 20 ft container, about 14 tonnes",
        note: "Main crop opens in October. Light crop material is available from about May but trades on a different basis.",
      },
      {
        name: "Cocoa powder",
        slug: "cocoa-powder",
        origins: ["Nigeria", "Ghana"],
        calendar: months([], ALL),
        unit: "Metric tonne",
        minimumOrder: "5 tonnes",
        note: "Natural and alkalised, processed at origin. Available from stock year round, subject to grinding capacity.",
      },
      {
        name: "Cocoa butter",
        slug: "cocoa-butter",
        origins: ["Nigeria", "Ghana"],
        calendar: months([], ALL),
        unit: "Metric tonne",
        minimumOrder: "5 tonnes",
        note: "Food grade and cosmetic grade are different products at different prices. State which before asking for a quotation.",
      },
    ],
  },
  {
    slug: "oils",
    name: "Oils",
    summary: "Palm, palm kernel, sesame and groundnut oil, available through the year.",
    intro:
      "Oils trade continuously rather than seasonally, with pricing that follows the underlying crop. Two questions decide whether a supplier is workable for the United Kingdom market: the level of refinement, and whether the material can be certified sustainable where that is required.",
    specify: [
      "Crude, semi refined or fully refined",
      "Free fatty acid content and moisture",
      "Food grade or cosmetic grade",
      "Packaging: drums, jerry cans, IBC or flexitank",
      "Sustainability certification where required",
    ],
    products: [
      {
        name: "Palm oil",
        slug: "palm-oil",
        origins: ["Nigeria", "Ghana", "Cameroon"],
        calendar: months([2, 3, 4, 5], except(2, 3, 4, 5)),
        unit: "Metric tonne",
        minimumOrder: "One flexitank, about 20 tonnes",
        note: "Crude and refined. Peak production runs February to May. Free fatty acid content is the number that decides the price.",
      },
      {
        name: "African palm kernel oil",
        slug: "palm-kernel-oil",
        origins: ["Nigeria", "Ghana"],
        calendar: months([2, 3, 4, 5], except(2, 3, 4, 5)),
        unit: "Metric tonne",
        minimumOrder: "5 tonnes",
        note: "Distinct from palm oil in composition and use. Sold into food manufacturing, soap and cosmetics.",
      },
      {
        name: "Sesame oil",
        slug: "sesame-oil",
        origins: ["Nigeria"],
        calendar: months([1, 2, 3], except(1, 2, 3)),
        unit: "Metric tonne",
        minimumOrder: "2 tonnes",
        note: "Cold pressed and refined. Best pricing follows the December to February seed crop.",
      },
      {
        name: "Groundnut oil",
        slug: "groundnut-oil",
        origins: ["Nigeria"],
        calendar: months([12, 1, 2], except(12, 1, 2)),
        unit: "Metric tonne",
        minimumOrder: "5 tonnes",
        note: "Cold pressed and refined. Aflatoxin testing applies to the oil as well as to the nut.",
      },
    ],
  },
  {
    slug: "roots-and-processed-foods",
    name: "Roots and processed foods",
    summary:
      "Garri, cassava flour and chips, yam and yam flour, plantain flour and potato.",
    intro:
      "This category serves the United Kingdom diaspora retail trade and the growing set of mainstream retailers stocking West African staples. Order sizes are smaller, turnover is faster, and labelling is the thing that most often stops a shipment at the border. Get the label right before the first order rather than after it.",
    specify: [
      "Retail pack size and case configuration",
      "Moisture content and shelf life remaining on arrival",
      "United Kingdom compliant labelling, including allergens and nutrition",
      "Barcode, and whether own label is possible",
      "Whether the producer holds a recognised food safety certification",
    ],
    products: [
      {
        name: "Garri",
        slug: "garri",
        origins: ["Nigeria", "Ghana"],
        calendar: months([], ALL),
        unit: "Carton",
        minimumOrder: "One pallet",
        note: "White and yellow. Moisture control decides shelf life, so ask what the producer measures and how often.",
      },
      {
        name: "Cassava flour",
        slug: "cassava-flour",
        origins: ["Nigeria", "Ghana"],
        calendar: months([], ALL),
        unit: "Carton",
        minimumOrder: "One pallet",
        note: "Includes fufu and pounded yam style flours. Growing mainstream demand as a gluten free ingredient.",
      },
      {
        name: "Yam",
        localName: "Isu, Ji, Doya",
        slug: "yam",
        origins: ["Nigeria", "Ghana"],
        calendar: months([10, 11, 12, 1], [2, 3, 9]),
        unit: "Carton or crate",
        minimumOrder: "One pallet",
        note: "Puna yam ships from about September through the winter. Handling and packing decide how much arrives saleable.",
      },
      {
        name: "Yam flour",
        slug: "yam-flour",
        origins: ["Nigeria"],
        calendar: months([], ALL),
        unit: "Carton",
        minimumOrder: "One pallet",
        note: "Elubo. Milled and packed at origin, available year round from stock.",
      },
      {
        name: "Plantain flour",
        slug: "plantain-flour",
        origins: ["Nigeria", "Ghana", "Uganda"],
        calendar: months([], ALL),
        unit: "Carton",
        minimumOrder: "One pallet",
        note: "Unripe plantain, milled. Packaging quality varies widely between producers, so ask for physical samples.",
      },
      {
        name: "Potato",
        slug: "potato",
        origins: ["Nigeria"],
        calendar: months([8, 9, 10], [3, 4, 11]),
        unit: "Bag or crate",
        minimumOrder: "One pallet",
        note: "Irish and sweet potato from the Plateau highlands. Main crop from August, with a smaller second window in spring.",
      },
      {
        name: "Cassava",
        localName: "Akpu, Rogo",
        slug: "cassava",
        origins: ["Nigeria", "Ghana", "Cote d Ivoire", "Mozambique", "Tanzania"],
        calendar: months([11, 12, 1, 2, 3], [4, 5, 6, 7, 8, 9, 10]),
        unit: "Metric tonne",
        minimumOrder: "20 to 25 tonnes of dried chips, one 20 ft container",
        note: "Fresh root, dried chips, flour or starch. Specify the form, moisture below 12 to 14 percent for chips, cyanide safety thresholds, and mesh size for flour.",
      },
      {
        name: "Sweet potato",
        localName: "Odunkun, Viazi Tamu",
        slug: "sweet-potato",
        origins: ["Egypt", "Nigeria", "South Africa", "Kenya"],
        calendar: months([8, 9, 10, 11, 12, 1], [2, 3, 4, 5, 6, 7]),
        unit: "Metric tonne",
        minimumOrder: "20 tonnes, one 40 ft reefer container",
        note: "Specify flesh colour, orange, white or purple, the curing state, root calibration by weight, and Brix level for sweetness.",
      },
      {
        name: "Cocoyam",
        localName: "Ede, Koko, Macabo",
        slug: "cocoyam",
        origins: ["Ghana", "Nigeria", "Cameroon", "Madagascar"],
        calendar: months([9, 10, 11, 12, 1, 2], [3, 4, 5, 6, 7, 8]),
        unit: "Metric tonne",
        minimumOrder: "5 to 10 tonnes",
        note: "Taro and cocoyam. Specify corm size, cormel count, moisture level, and whether the crop is washed or dry brushed.",
      },
      {
        name: "Fluted pumpkin seed",
        localName: "Ugu, Ikperikpe",
        slug: "ugu-seed",
        origins: ["Nigeria", "Ghana"],
        calendar: months([10, 11, 12], [1, 2, 3, 4, 5, 6, 7, 8, 9]),
        unit: "Metric tonne",
        minimumOrder: "5 tonnes of dried seed",
        note: "Dried ugu seed. Specify shelled or in shell, dryness, and freedom from mould.",
      },
      {
        name: "White garri",
        localName: "Garri Funfun, Ijebu garri",
        slug: "white-garri",
        origins: ["Nigeria", "Ghana"],
        calendar: months([], ALL),
        unit: "Carton",
        minimumOrder: "One pallet",
        note: "Fine grained sour variety. Specify grain size, sourness, moisture and pack format. Ijebu garri commands a premium in diaspora retail.",
      },
      {
        name: "Yellow garri",
        localName: "Garri Pupa",
        slug: "yellow-garri",
        origins: ["Nigeria", "Ghana"],
        calendar: months([], ALL),
        unit: "Carton",
        minimumOrder: "One pallet",
        note: "Fried with palm oil, giving the colour. Specify oil content, grain size and moisture.",
      },
      {
        name: "Red garri",
        localName: "Garri Pupa Dudu",
        slug: "red-garri",
        origins: ["Nigeria"],
        calendar: months([], ALL),
        unit: "Carton",
        minimumOrder: "One pallet",
        note: "Heavier palm oil content than yellow garri. Specify grain size, oil content and shelf life remaining on arrival.",
      },
      {
        name: "Pounded yam flour",
        localName: "Poundo, Elubo Isu",
        slug: "pounded-yam-flour",
        origins: ["Nigeria"],
        calendar: months([], ALL),
        unit: "Carton",
        minimumOrder: "One pallet",
        note: "Instant yam flour. Specify pack size, particle fineness, and United Kingdom compliant labelling including allergens.",
      },
      {
        name: "Semolina",
        localName: "Semolina",
        slug: "semolina",
        origins: ["Nigeria"],
        calendar: months([], ALL),
        unit: "Carton",
        minimumOrder: "One pallet",
        note: "Durum wheat semolina for swallow preparation. Specify granulation, protein content and pack size. Sold under the generic name rather than any brand.",
      },
      {
        name: "Tapioca",
        localName: "Tapioca, Abacha",
        slug: "tapioca",
        origins: ["Nigeria"],
        calendar: months([], ALL),
        unit: "Carton",
        minimumOrder: "One pallet",
        note: "Dried cassava flakes and strips. Specify whether flake or shredded strip, moisture and pack format.",
      },
      {
        name: "Fufu flour",
        localName: "Akpu, Fufu",
        slug: "fufu-flour",
        origins: ["Nigeria", "Ghana"],
        calendar: months([], ALL),
        unit: "Carton",
        minimumOrder: "One pallet",
        note: "Fermented cassava flour. Specify fermentation level, odour control in packaging and shelf life.",
      },
      {
        name: "Ogi",
        localName: "Ogi, Akamu, Pap",
        slug: "ogi",
        origins: ["Nigeria"],
        calendar: months([], ALL),
        unit: "Carton",
        minimumOrder: "One pallet",
        note: "Fermented maize or millet starch. Specify base grain, whether wet or dried, and shelf life on arrival.",
      },
      {
        name: "Cocoyam flour",
        localName: "Achicha, Elubo Koko",
        slug: "cocoyam-flour",
        origins: ["Nigeria", "Ghana"],
        calendar: months([], ALL),
        unit: "Carton",
        minimumOrder: "One pallet",
        note: "Milled and dried cocoyam. Specify particle size, moisture and pack format.",
      },
      {
        name: "Chin chin",
        localName: "Chin chin",
        slug: "chin-chin",
        origins: ["Nigeria", "Ghana"],
        calendar: months([], ALL),
        unit: "Carton",
        minimumOrder: "One pallet",
        note: "Fried wheat snack. Specify pack size, shelf life, allergen declaration and whether own label packing is available.",
      },
      {
        name: "Plantain chips",
        localName: "Ipekere, Dodo Ikire",
        slug: "plantain-chips",
        origins: ["Nigeria", "Ghana"],
        calendar: months([], ALL),
        unit: "Carton",
        minimumOrder: "One pallet",
        note: "Specify sweet or savoury, thickness, oil used for frying and United Kingdom compliant labelling.",
      },
      {
        name: "Kuli kuli",
        localName: "Kuli kuli",
        slug: "kuli-kuli",
        origins: ["Nigeria"],
        calendar: months([], ALL),
        unit: "Carton",
        minimumOrder: "One pallet",
        note: "Groundnut cake snack. Specify aflatoxin testing, oil content and pack format.",
      },
    ],
  },
  {
    slug: "fresh-vegetables",
    name: "Fresh vegetables and leaves",
    summary:
      "Ugu, bitterleaf, okra and garden egg, air freighted fresh or shipped dried and frozen.",
    intro:
      "Fresh leaves and vegetables are the fastest moving goods on the platform and the least forgiving. Most travel by air, arrive within days and are judged on condition rather than on grade. The two things that decide whether a shipment is saleable are the cold chain and the phytosanitary paperwork, and both need agreeing before the first order rather than after it.",
    specify: [
      "Fresh, washed, dried or frozen",
      "Cold chain requirement and temperature range in transit",
      "Phytosanitary certification and pest free status",
      "Pack format, carton weight and ventilation",
      "Shelf life remaining on arrival",
    ],
    products: [
      {
        name: "Fluted pumpkin leaves",
        localName: "Ugu, Ikperikpe",
        slug: "ugu",
        origins: ["Nigeria", "Ghana"],
        calendar: months([5, 6, 7, 8, 9, 10], [1, 2, 3, 4, 11, 12]),
        unit: "Kilogram",
        minimumOrder: "500 kg fresh by air freight",
        note: "Specify cold chain packaging, leaf integrity and pest free phytosanitary status. Peak leaf season runs through the rains from May to October.",
      },
      {
        name: "Bitterleaf",
        localName: "Onugbu, Ewuro, Ndole",
        slug: "bitterleaf",
        origins: ["Nigeria", "Cameroon", "Ghana"],
        calendar: months([5, 6, 7, 8, 9, 10], [1, 2, 3, 4, 11, 12]),
        unit: "Kilogram",
        minimumOrder: "250 to 500 kg fresh or frozen by air",
        note: "Specify the state, whether fresh whole leaf, washed and squeezed to reduce bitterness, dried, or frozen.",
      },
      {
        name: "Okra",
        localName: "Ila, Okwuru, Gumbo",
        slug: "okra",
        origins: ["Egypt", "Kenya", "Ghana", "Nigeria"],
        calendar: months([11, 12, 1, 2, 3, 4, 5], [6, 7, 8, 9, 10]),
        unit: "Kilogram",
        minimumOrder: "1 to 2 tonnes fresh by air freight",
        note: "Specify pod calibration, baby okra against standard at 5 to 9 cm, pod colour, straightness and absence of fibre.",
      },
      {
        name: "Garden egg",
        localName: "Anara, Gauta",
        slug: "garden-egg",
        origins: ["Ghana", "Nigeria", "Uganda", "Kenya"],
        calendar: months([6, 7, 8, 9, 10, 11], [1, 2, 3, 4, 5, 12]),
        unit: "Kilogram",
        minimumOrder: "1 tonne by air freight",
        note: "African eggplant. Specify fruit colour, white, green or striped, the species, Solanum aethiopicum or gilo, size and skin firmness.",
      },
      {
        name: "Tomatoes",
        localName: "Tomati",
        slug: "tomatoes",
        origins: ["Nigeria", "Ghana", "Egypt", "Morocco"],
        calendar: months([11, 12, 1, 2, 3], [4, 10]),
        unit: "Kilogram",
        minimumOrder: "1 tonne by air freight",
        note: "Highly perishable and usually sourced closer to market. Specify variety, caliber, firmness and cold chain range before committing to a shipment.",
      },
      {
        name: "Onions",
        localName: "Alubosa, Albasa",
        slug: "onions",
        origins: ["Nigeria", "Niger", "Egypt"],
        calendar: months([3, 4, 5], [1, 2, 6, 12]),
        unit: "Metric tonne",
        minimumOrder: "5 tonnes",
        note: "Specify bulb size, cured status, skin retention and storage life. Northern Nigerian and Nigerien crop arrives from March.",
      },
      {
        name: "Scotch bonnet",
        localName: "Ata Rodo",
        slug: "scotch-bonnet",
        origins: ["Nigeria", "Ghana"],
        calendar: months([11, 12, 1, 2], [3, 10]),
        unit: "Kilogram",
        minimumOrder: "500 kg by air freight",
        note: "Very high heat. Specify colour, firmness, fresh or frozen, and cold chain range in transit.",
      },
      {
        name: "Cayenne pepper",
        localName: "Shombo",
        slug: "cayenne-pepper",
        origins: ["Nigeria", "Ghana"],
        calendar: months([11, 12, 1, 2], [3, 10]),
        unit: "Kilogram",
        minimumOrder: "500 kg by air freight",
        note: "Long red chilli, moderate heat. Specify fresh, dried or ground, and the pod length.",
      },
      {
        name: "Red bell pepper",
        localName: "Tatashe",
        slug: "tatashe",
        origins: ["Nigeria", "Ghana"],
        calendar: months([11, 12, 1, 2], [3, 10]),
        unit: "Kilogram",
        minimumOrder: "500 kg by air freight",
        note: "Mild sweet pepper used as the base of most Nigerian stews. Specify size, colour and firmness at dispatch.",
      },
      {
        name: "Waterleaf",
        localName: "Gbure, Mgbolodi",
        slug: "waterleaf",
        origins: ["Nigeria"],
        calendar: months([5, 6, 7, 8, 9], [4, 10]),
        unit: "Kilogram",
        minimumOrder: "250 kg by air freight",
        note: "Extremely perishable. Specify cold chain range, packing format and expected shelf life on arrival.",
      },
      {
        name: "Ewedu",
        localName: "Ewedu, Ayoyo",
        slug: "ewedu",
        origins: ["Nigeria", "Ghana"],
        calendar: months([5, 6, 7, 8, 9], [4, 10]),
        unit: "Kilogram",
        minimumOrder: "250 kg fresh or frozen",
        note: "Jute mallow leaf. Specify fresh, frozen or dried, and whether shredded.",
      },
      {
        name: "Utazi",
        localName: "Utazi",
        slug: "utazi",
        origins: ["Nigeria"],
        calendar: months([5, 6, 7, 8, 9], [1, 2, 3, 4, 10, 11, 12]),
        unit: "Kilogram",
        minimumOrder: "100 kg",
        note: "Bitter leaf used in small quantities. Specify fresh, dried or ground, and leaf integrity.",
      },
      {
        name: "Uziza leaf",
        localName: "Uziza",
        slug: "uziza-leaf",
        origins: ["Nigeria"],
        calendar: months([5, 6, 7, 8, 9], [4, 10]),
        unit: "Kilogram",
        minimumOrder: "100 kg",
        note: "Specify fresh or dried, and whether whole leaf or shredded.",
      },
      {
        name: "Okazi",
        localName: "Okazi, Afang, Ukazi",
        slug: "okazi",
        origins: ["Nigeria", "Cameroon"],
        calendar: months([], ALL),
        unit: "Kilogram",
        minimumOrder: "250 kg",
        note: "Gnetum africanum leaf. Specify fresh, shredded or dried. Wild harvested, so supply is uneven and worth confirming before pricing.",
      },
      {
        name: "Oha leaf",
        localName: "Oha, Ora",
        slug: "oha-leaf",
        origins: ["Nigeria"],
        calendar: months([3, 4, 5], [2, 6, 7]),
        unit: "Kilogram",
        minimumOrder: "100 kg",
        note: "Specify fresh or dried, leaf maturity and packing format for air freight.",
      },
      {
        name: "Scent leaf",
        localName: "Efirin, Nchanwu, Daidoya",
        slug: "scent-leaf",
        origins: ["Nigeria", "Ghana"],
        calendar: months([], ALL),
        unit: "Kilogram",
        minimumOrder: "100 kg",
        note: "African basil. Specify fresh, dried or ground, and the drying method, since aroma is lost with heat.",
      },
      {
        name: "African spinach",
        localName: "Tete, Green",
        slug: "african-spinach",
        origins: ["Nigeria", "Ghana"],
        calendar: months([5, 6, 7, 8, 9], [4, 10]),
        unit: "Kilogram",
        minimumOrder: "250 kg",
        note: "Amaranth leaf. Specify fresh or frozen, leaf maturity and cold chain requirement.",
      },
      {
        name: "Lagos spinach",
        localName: "Soko",
        slug: "lagos-spinach",
        origins: ["Nigeria"],
        calendar: months([5, 6, 7, 8, 9], [4, 10]),
        unit: "Kilogram",
        minimumOrder: "250 kg",
        note: "Celosia argentea. Specify fresh or frozen, and packing format.",
      },
      {
        name: "Cassava leaves",
        localName: "Ewe Ege, Pondu",
        slug: "cassava-leaves",
        origins: ["Nigeria", "Ghana", "Cameroon"],
        calendar: months([], ALL),
        unit: "Kilogram",
        minimumOrder: "250 kg",
        note: "Specify fresh, pounded or frozen. Must be properly processed before consumption, so state the preparation stage supplied.",
      },
      {
        name: "Moringa leaves",
        localName: "Zogale, Ewe Igbale",
        slug: "moringa-leaves",
        origins: ["Nigeria", "Ghana"],
        calendar: months([], ALL),
        unit: "Kilogram",
        minimumOrder: "250 kg",
        note: "Specify fresh, shade dried leaf or powder, along with mesh size for powder and microbial limits.",
      },
    ],
  },
  {
    slug: "fresh-fruit",
    name: "Fresh fruit",
    summary:
      "Agbalumo, ube, avocado and citrus, moving by air for the short lived crops and by reefer for the rest.",
    intro:
      "Fruit divides into two trades. Agbalumo and ube have short shelf lives, sell into diaspora retail and move by air within days of picking. Avocado and citrus are established reefer commodities with published grade standards, where the buyer is checking dry matter, caliber and certification rather than freshness. Price the two differently, because they are not the same business.",
    specify: [
      "Variety, and caliber or count per carton",
      "Ripeness stage at dispatch and expected shelf life",
      "Cold chain temperature range and logger requirement",
      "Certification, including GlobalG.A.P. where required",
      "Treatment for fruit fly compliance where applicable",
    ],
    products: [
      {
        name: "African star apple",
        localName: "Agbalumo, Udara",
        slug: "african-star-apple",
        origins: ["Nigeria", "Ghana", "Benin"],
        calendar: months([12, 1, 2, 3]),
        unit: "Kilogram",
        minimumOrder: "500 kg to 1 tonne by air, given the short shelf life",
        note: "Specify the ripeness stage, which must be firm ripe to survive transit, the skin damage allowance and size calibration.",
      },
      {
        name: "African pear",
        localName: "Ube, Safou",
        slug: "ube",
        origins: ["Nigeria", "Cameroon", "Gabon", "Republic of Congo"],
        calendar: months([5, 6, 7, 8, 9, 10]),
        unit: "Kilogram",
        minimumOrder: "500 kg to 1 tonne by air freight",
        note: "Bush butter fruit. Specify pulp thickness, size grading, firmness at dispatch and the cold chain conditions required in transit.",
      },
      {
        name: "Avocado",
        localName: "Parachichi",
        slug: "avocado",
        origins: ["Kenya", "South Africa", "Tanzania", "Morocco"],
        calendar: months([3, 4, 5, 6, 7, 8, 9], [1, 2, 10, 11, 12]),
        unit: "Metric tonne",
        minimumOrder: "20 tonnes, one 40 ft reefer container",
        note: "Specify the variety, Hass or Fuerte, the count per 4 kg box, dry matter above 21 to 23 percent for proper ripening, and GlobalG.A.P. certification.",
      },
      {
        name: "Citrus",
        localName: "Oloma, Osan",
        slug: "citrus",
        origins: ["South Africa", "Egypt", "Morocco", "Ghana"],
        calendar: months([5, 6, 7, 8, 9, 10], [1, 2, 3, 4, 11, 12]),
        unit: "Metric tonne",
        minimumOrder: "20 to 24 tonnes, one 40 ft reefer container",
        note: "Oranges, lemons and grapefruit. Specify the variety, caliber count, juice content percentage, Brix to acid ratio and waxing standard.",
      },
      {
        name: "Mango",
        localName: "Mangoro",
        slug: "mango",
        origins: ["Nigeria", "Ghana", "Cote d Ivoire", "Kenya", "Egypt"],
        calendar: months([4, 5, 6, 7], [3, 8]),
        unit: "Metric tonne",
        minimumOrder: "15 tonnes, one 40 ft reefer container",
        note: "Specify variety, Kent, Keitt or apple mango, Brix above 12 degrees, and hot water or vapour heat treatment for fruit fly compliance.",
      },
      {
        name: "Pineapple",
        localName: "Ope Oyinbo",
        slug: "pineapple",
        origins: ["Ghana", "Cote d Ivoire", "Nigeria", "Kenya"],
        calendar: months([], ALL),
        unit: "Metric tonne",
        minimumOrder: "18 to 20 tonnes, one 40 ft reefer container",
        note: "Specify variety, MD2 or Smooth Cayenne, crown ratio, shell colour on the one to four scale and Brix above 12 degrees.",
      },
      {
        name: "Plantain",
        localName: "Ogede Agbagba, Abrodwomaa",
        slug: "plantain",
        origins: ["Nigeria", "Ghana", "Cote d Ivoire"],
        calendar: months([], ALL),
        unit: "Metric tonne",
        minimumOrder: "5 tonnes",
        note: "Specify green or ripe at dispatch, finger count per bunch, and the cold chain range required to hold the ripening stage.",
      },
      {
        name: "Banana",
        localName: "Ogede, Kwadu",
        slug: "banana",
        origins: ["Nigeria", "Ghana", "Cameroon"],
        calendar: months([], ALL),
        unit: "Metric tonne",
        minimumOrder: "18 tonnes, one 40 ft reefer container",
        note: "Specify caliber, finger length, ripening stage at dispatch and cold chain range.",
      },
      {
        name: "Pawpaw",
        localName: "Ibepe, Gwanda",
        slug: "pawpaw",
        origins: ["Nigeria", "Ghana"],
        calendar: months([], ALL),
        unit: "Kilogram",
        minimumOrder: "1 tonne by air freight",
        note: "Papaya. Specify variety, ripeness stage, size calibration and cold chain range.",
      },
      {
        name: "Guava",
        localName: "Gova",
        slug: "guava",
        origins: ["Nigeria", "Ghana"],
        calendar: months([8, 9, 10, 11], [7, 12]),
        unit: "Kilogram",
        minimumOrder: "1 tonne by air freight",
        note: "Specify variety, flesh colour, ripeness at dispatch and expected shelf life.",
      },
      {
        name: "Soursop",
        localName: "Ebo, Tuwon Biri",
        slug: "soursop",
        origins: ["Nigeria", "Ghana"],
        calendar: months([6, 7, 8, 9], [5, 10]),
        unit: "Kilogram",
        minimumOrder: "500 kg by air freight, or pulp by reefer",
        note: "Very short shelf life as fresh fruit. Specify whether fresh, frozen pulp or dried leaf.",
      },
      {
        name: "Watermelon",
        localName: "Bara",
        slug: "watermelon",
        origins: ["Nigeria", "Ghana", "Egypt"],
        calendar: months([11, 12, 1, 2], [3, 10]),
        unit: "Metric tonne",
        minimumOrder: "20 tonnes, one 40 ft reefer container",
        note: "Specify variety, average fruit weight, Brix and rind thickness for transit durability.",
      },
      {
        name: "Velvet tamarind",
        localName: "Icheku, Awin",
        slug: "velvet-tamarind",
        origins: ["Nigeria", "Ghana"],
        calendar: months([11, 12, 1], [2, 10]),
        unit: "Kilogram",
        minimumOrder: "250 kg",
        note: "Dialium guineense. Specify whole pods or extracted pulp, dryness and packing format.",
      },
      {
        name: "Tamarind",
        localName: "Tsamiya, Ajagbon",
        slug: "tamarind",
        origins: ["Nigeria", "Ghana", "Senegal"],
        calendar: months([1, 2, 3], [4, 12]),
        unit: "Metric tonne",
        minimumOrder: "2 tonnes",
        note: "Specify whole pod, de shelled pulp or seedless block, along with moisture and any sugar addition.",
      },
      {
        name: "Baobab fruit",
        localName: "Kuka, Ose",
        slug: "baobab-fruit",
        origins: ["Nigeria", "Ghana", "Senegal", "Malawi"],
        calendar: months([3, 4, 5], [2, 6]),
        unit: "Metric tonne",
        minimumOrder: "1 tonne",
        note: "Specify whole pod, pulp powder or seed. For powder specify mesh size, moisture and microbial limits.",
      },
      {
        name: "African breadfruit",
        localName: "Ukwa",
        slug: "african-breadfruit",
        origins: ["Nigeria"],
        calendar: months([4, 5, 6], [3, 7]),
        unit: "Kilogram",
        minimumOrder: "500 kg",
        note: "Treculia africana seed. Specify shelled or in shell, dryness and freedom from weevil.",
      },
      {
        name: "Passion fruit",
        localName: "Passion fruit",
        slug: "passion-fruit",
        origins: ["Kenya", "Uganda", "Nigeria"],
        calendar: months([3, 4, 5, 9, 10], [1, 2, 6]),
        unit: "Kilogram",
        minimumOrder: "1 tonne by air freight",
        note: "Specify variety, purple or yellow, fruit size, skin condition and juice recovery percentage.",
      },
      {
        name: "Lime",
        localName: "Osan Wewe",
        slug: "lime",
        origins: ["Nigeria", "Ghana"],
        calendar: months([9, 10, 11, 12], [1, 8]),
        unit: "Metric tonne",
        minimumOrder: "5 tonnes",
        note: "Specify caliber, juice content, skin colour and treatment or waxing standard.",
      },
      {
        name: "Coconut water",
        localName: "Omi Agbon",
        slug: "coconut-water",
        origins: ["Nigeria", "Ghana", "Tanzania"],
        calendar: months([], ALL),
        unit: "Metric tonne",
        minimumOrder: "5 tonnes",
        note: "Specify whether in nut, bottled or bulk aseptic, along with Brix, pasteurisation method and shelf life.",
      },
    ],
  },
  {
    slug: "seafood-and-animal-products",
    name: "Seafood and animal products",
    summary: "Dried and smoked fish, prawns, honey, beeswax and hides and skins.",
    intro:
      "This is the most tightly regulated category on the platform. Fish and animal products entering the United Kingdom must come from an approved establishment, and honey is subject to residue testing. Establish the approvals before you negotiate a price, because without them the goods cannot land at any price.",
    specify: [
      "The producer's approved establishment number for United Kingdom import",
      "Species, size grade and packing format",
      "Moisture content for dried fish, and residue testing for honey",
      "Cold chain requirements where applicable",
      "Shelf life remaining on arrival",
    ],
    products: [
      {
        name: "Dried fish",
        slug: "dried-fish",
        origins: ["Nigeria", "Ghana"],
        calendar: months([], ALL),
        unit: "Carton",
        minimumOrder: "One pallet",
        note: "Stockfish, catfish and tilapia. An approved establishment number is required for import into the United Kingdom. Confirm it before ordering.",
      },
      {
        name: "Smoked fish",
        slug: "smoked-fish",
        origins: ["Nigeria", "Ghana"],
        calendar: months([], ALL),
        unit: "Carton",
        minimumOrder: "One pallet",
        note: "Sold mainly into diaspora retail. Same approval requirement as dried fish, and moisture control decides shelf life.",
      },
      {
        name: "Prawns",
        slug: "prawns",
        origins: ["Nigeria"],
        calendar: months([7, 8, 9, 10], [6, 11]),
        unit: "Carton",
        minimumOrder: "One pallet",
        note: "Dried and frozen. Size grade drives the price. Frozen product needs an unbroken cold chain and the paperwork to prove it.",
      },
      {
        name: "Honey",
        slug: "honey",
        origins: ["Nigeria", "Cameroon"],
        calendar: months([12, 1, 2, 3], [11, 4]),
        unit: "Metric tonne",
        minimumOrder: "1 tonne",
        note: "Raw and filtered. United Kingdom import requires residue testing, and buyers increasingly ask for pollen analysis to confirm origin.",
      },
      {
        name: "Beeswax",
        slug: "beeswax",
        origins: ["Nigeria", "Cameroon"],
        calendar: months([12, 1, 2, 3], [11, 4]),
        unit: "Metric tonne",
        minimumOrder: "1 tonne",
        note: "Crude and refined blocks, following the honey harvest. Sold into cosmetics, candles and food coating.",
      },
      {
        name: "Hides and skins",
        slug: "hides-and-skins",
        origins: ["Nigeria"],
        calendar: months([], ALL),
        unit: "Metric tonne",
        minimumOrder: "One 20 ft container",
        note: "Wet salted and dried. Veterinary health certification is required for import, and grade depends heavily on flaying quality.",
      },
      {
        name: "Crayfish",
        localName: "Ede, Oporo",
        slug: "crayfish",
        origins: ["Nigeria", "Ghana", "Cameroon"],
        calendar: months([], ALL),
        unit: "Kilogram",
        minimumOrder: "500 kg",
        note: "Dried and ground or whole. Specify size grade, whether whole or powdered, moisture, and the approved establishment number for United Kingdom import.",
      },
      {
        name: "Stockfish",
        localName: "Okporoko, Panla",
        slug: "stockfish",
        origins: ["Nigeria", "Norway"],
        calendar: months([], ALL),
        unit: "Carton",
        minimumOrder: "One pallet",
        note: "Dried cod head and body. Specify cut, grade, moisture, and the approved establishment number for import.",
      },
      {
        name: "Dried catfish",
        localName: "Eja Aro",
        slug: "dried-catfish",
        origins: ["Nigeria", "Ghana"],
        calendar: months([], ALL),
        unit: "Carton",
        minimumOrder: "One pallet",
        note: "Specify size grade, smoking method, moisture and the approved establishment number for United Kingdom import.",
      },
      {
        name: "Bonga fish",
        localName: "Shawa",
        slug: "bonga-fish",
        origins: ["Nigeria", "Ghana"],
        calendar: months([], ALL),
        unit: "Carton",
        minimumOrder: "One pallet",
        note: "Smoked ethmalosa. Specify size grade, smoking method and packaging, plus the establishment approval required for import.",
      },
      {
        name: "Periwinkle",
        localName: "Isam, Mfi",
        slug: "periwinkle",
        origins: ["Nigeria"],
        calendar: months([], ALL),
        unit: "Kilogram",
        minimumOrder: "250 kg",
        note: "Specify in shell or shelled, fresh, frozen or dried, and the cold chain requirement where applicable.",
      },
      {
        name: "Snail",
        localName: "Igbin, Congo meat",
        slug: "snail",
        origins: ["Nigeria", "Ghana"],
        calendar: months([5, 6, 7, 8, 9], [4, 10]),
        unit: "Kilogram",
        minimumOrder: "250 kg",
        note: "Giant African land snail. Specify live, frozen or dried, size grade and the veterinary certification required for import.",
      },
    ],
  },
];

export interface Origin {
  country: string;
  region: string;
  knownFor: string;
}

export const ORIGINS: Origin[] = [
  { country: "Nigeria", region: "West Africa", knownFor: "Sesame, ginger, hibiscus, cashew, palm oil, cassava products" },
  { country: "Ghana", region: "West Africa", knownFor: "Cocoa, shea, cassava products, dried fish" },
  { country: "Cote d Ivoire", region: "West Africa", knownFor: "Cocoa, cashew" },
  { country: "Cameroon", region: "Central Africa", knownFor: "Cocoa, palm oil, honey" },
  { country: "Kenya", region: "East Africa", knownFor: "Herbs, honey, horticultural produce" },
  { country: "Uganda", region: "East Africa", knownFor: "Sesame, dried fruit, plantain products" },
  { country: "Tanzania", region: "East Africa", knownFor: "Cashew, sesame" },
  { country: "Ethiopia", region: "East Africa", knownFor: "Sesame, pulses, spices" },
  { country: "Benin", region: "West Africa", knownFor: "Cashew, egusi, cocoa" },
  { country: "Burkina Faso", region: "West Africa", knownFor: "Sesame, shea, cowpea, bambara groundnut" },
  { country: "Egypt", region: "North Africa", knownFor: "Okra, citrus, sweet potato" },
  { country: "Eritrea", region: "East Africa", knownFor: "Teff" },
  { country: "Gabon", region: "Central Africa", knownFor: "Ogbono, African pear" },
  { country: "Guinea", region: "West Africa", knownFor: "Fonio" },
  { country: "Guinea-Bissau", region: "West Africa", knownFor: "Cashew" },
  { country: "Madagascar", region: "East Africa", knownFor: "Rice, cocoyam" },
  { country: "Malawi", region: "Southern Africa", knownFor: "Groundnut" },
  { country: "Mali", region: "West Africa", knownFor: "Fonio, shea, tiger nut" },
  { country: "Morocco", region: "North Africa", knownFor: "Citrus, avocado" },
  { country: "Mozambique", region: "Southern Africa", knownFor: "Cassava, cowpea" },
  { country: "Niger", region: "West Africa", knownFor: "Tiger nut, millet" },
  { country: "Republic of Congo", region: "Central Africa", knownFor: "African pear" },
  { country: "Senegal", region: "West Africa", knownFor: "Groundnut, fonio" },
  { country: "Sierra Leone", region: "West Africa", knownFor: "Rice" },
  { country: "South Africa", region: "Southern Africa", knownFor: "Citrus, avocado, sorghum" },
  { country: "Sudan", region: "North Africa", knownFor: "Sesame, sorghum, groundnut" },
  { country: "Zimbabwe", region: "Southern Africa", knownFor: "Bambara groundnut" },
];

export function getCategory(slug: string): Category | undefined {
  return CATEGORIES.find((c) => c.slug === slug);
}

/** Aggregate a category's product calendars into one twelve month row. */
export function categoryCalendar(category: Category): Availability[] {
  return Array.from({ length: 12 }, (_, i) => {
    const cells = category.products.map((p) => p.calendar[i]);
    if (cells.includes("peak")) return "peak";
    if (cells.includes("available")) return "available";
    return "none";
  });
}
